import React, { Component } from 'react';
import '../App.css';

class Paper extends Component {
    render() {
        return(
            <div className="Main">
                <section className='title white'>
                  <div className="container">
                        <div className='contentTitle'>
                          <img class='erik' src={require('../images/gqom.png')} />
                        </div>
                        
                                    
                        <h2>Erik Bergstrom</h2>
                                       
                        <p>The futuristic dance style of gqom, with its broken beats, dark drones, and growling samples, has had an interesting evolution since its rise in the clubs of Durban. Gqom became popular in Europe long before it was widely popular in its native South Africa, partially due to its  Through the "gqomwave" music of Okmalumkoolkat, aka Smiso Zwane, gqom has demonstrated its portability as a genre, woven into American trap and hip-hop aesthetics. Okmalumkoolkat's collaboration with Rudeboyz shows Zwane's willingness to experiment with all of the styles and genres surrounding him. </p>
                    </div>
                </section>

                <section className='content paper black'>

	               <div class="container">
	              	<p>It has been almost two years since Nan Kolé’s Gqom Oh! label dropped “The Sound Durban, Vol. 1” compilation of gqom, introducing many in Europe and the US underground to the young producers creating the dark, entrancing, heavy sounds of gqom. Today, gqom as a style seems to be at a crossroads. In a similar narrative to how many dance genres around the world seem to age, gqom has had to fight its way out of Durban to make itself popular to listeners across South Africa. Faced with a lack of radio airtime, a conservative stigma against the music as drug-associated, and an abundant supply of similar sounding gqom tracks available for download, gqom artists have been forced to diverge, diversify, and develop their sounds and styles to adapt to a changing landscape and break through. Gqom was labeled “the apocalyptic sound of electronic music” by Kolé, but gqom artists today represent the post-apocalyptic future of the sounds of Durban. <br/> <br/>
                    Sghubu is one such evolution of gqom, and can be classified as a subgenre unto itself. Compared to the droning and harmonically static atmospheres of gqom, sghubu takes on more melodic lines. The tumbling, floating, broken beats of gqom are often softened up a little to sound more like traditional dance forms like house or kwaito. The Distruction Boyz, a duo consisting of Thobani “Que” Mgobhozi and Zipho “Gold” Mthembu dropped their debut album “Gqom is the Future” in October of 2017 with a very explicit goal: to go gold in South Africa. With all of the resistance facing gqom in terms of dissemination, the Distruction Boyz found a way around by bending their gqom tracks into bright synth-laden, at times four-on-the-floor sghubu tracks. One example of this is their viral hit “Omunye” on “Gqom is the Future”.</p>

                    <iframe src="https://www.youtube.com/embed/Npw4M2XLZK0?rel=0" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
                    <p>“Omunye” was a hit in South Africa, and even sparked a viral online dance trend, and from the sounds and rhythms of the track it is easy to see why. “Omunye” retains the slapping drum sounds and slightly off rhythm feel of gqom, but does not seem to fully embrace it. Instead of feeling like floating from beat to beat, getting tossed about by each one, the beat in “Omunye” seems much more grounded and stable. At times there is a four-on-the-floor kick, but it is dressed up with other syncopated rhythms around it. In this way, the rhythms reference house, without fully submitting to a house form. The synth sounds are also much brighter than any sounds that would be found in older gqom tracks. The rising and falling chords heard throughout sound almost like a repressed EDM synth anthem trying to break into the track, but to no avail, again referencing house sonic vocabulary without completely submitting to it. As a result of the bright synth lines and a less atmospheric tone, with less dark, mangled kwaito samples barking and grunting, the general feel of gqom is preserved but is washed in the colors of house. As house is the dominant pop music form in South Africa, the house-like characteristics of “Omunye” are likely what helped propel it to hit status in South Africa. <br/> <br/>
                    The Distruction Boyz also produced another South African hit with self-proclaimed gqom queen Babes Wodumo, whose track “Wololo” saw widespread popularity and became a party anthem in 2016. </p>
                    <iframe src="https://www.youtube.com/embed/hlkybvVEQ4g?rel=0" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
                    <p>Babes Wodumo, born Bongekile Simelane, has had a meteoric rise this year. From the release of her first album “Gqom Queen Vol. 1” in November 2016, to her nomination for a BET Award as the Best International Act in Africa, Wodumo shows no sign of stopping in her efforts to bring her take on the sounds of Durban to the rest of South Africa and the world. The Distruction Boyz beat for “Wololo” has much in common with the beat of “Omunye”, but with a harder edge. The track opens with a classic gqom beat, the kicks centered squarely on beats 1 and 2 to ground the beat, but with syncopated vocal samples and snare hits to create that floating gqom rhythm. Slowly and cautiously through the first chorus, a supersaw synth lead creeps in to supplement the already present string drone. The new supersaw drone stays repressed, like the anthemic synth line in “Omunye”, never consuming the mix like in other dance styles. The supersaw drone also give the track some harmonic motion, jumping up occasionally to the minor third, fourth, or fifth degrees. As rapper Mampintsha’s verse enters, a distant, arpeggiated synth comes in and repeats for the most of the track. This repetition preserves the ever-present tension of gqom, while adding an element of melody to the normally static and octave-based harmony of gqom. Just like in “Omunye”, the Distruction Boyz soften up some of the more challenging aspects of gqom and utilize sonic vocabulary borrowed from other electronic dance music in an attempt to package the unique character of the sound of Durban into a more consumer friendly style. <br/> <br/>
                    Babes Wodumo’s Zulu hooks and lines on the track ride this catchy, palatable style. Her doubled vocals create a powerful presence, as if the vocals are surrounding the listener along with the drums and drones. Wodumo’s voice on the track is welcome not just for its catchiness and addition of coherence to the beat, but also because she is a woman becoming a star in an otherwise completely male-dominated genre. Wodumo has now had major hits and acclaim for herself (and even some controversy, with her track “Mercedes” banned from radio for referencing a popular brand of ecstasy), all within two years of dropping her first singles, and a large part of this may be because of her unique status as the default queen of gqom. It is exciting to think that Babes Wodumo may be paving the way for other women to not just dance and sing on top of gqom beats, but produce and DJ as well, bringing new perspectives and voices to a growing style. <br/> <br/>
                    Distruction Boyz have clearly crossed into the mainstream with these tracks and others, with their grounded yet syncopated beats and choice of synth sounds bending the style of gqom into a more marketable brand. Their sghubu beats do not have the same paranoid darkness to them that other gqom tracks seem to have, and as such, they do not convey the same sense of environment that other, harder gqom does. The Distruction Boyz take pride in their environment, hometown, and origins, and package the danceability and energy of gqom without all of the angry and tense sonic baggage that it seems to come with. Sghubu represents one side of the developing spectrum of gqom as artists fan out and explore independent variations. 
                    While the Distruction Boyz continue their quest for gold and to build a legitimate brand for themselves, other artists are experimenting with different methods of transforming gqom into evolved styles. Okmalumkoolkat’s “Gqi!”, produced by none other than gqom mainstays Rudeboyz and released as the second single off of Okmalumkoolkat’s 2016 genre roller coaster album “Mlazi Milano”, became a hit in South Africa with its fusion of American hip-hop and trap styles with the sounds of gqom. </p>
                    <iframe src="https://www.youtube.com/embed/oMdHij9gRek?rel=0" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
                    <p>Okmalumkoolkat, also known as Smiso Zwane, has been known by many names and has a broad range of styles and personas in his past work. Best known as one-half of the experimental hip-hop group Dirty Paraffin, Zwane has also performed with British dance music trio LV. The album “Mlazi Milano” is Zwane’s first full length album as Okmalumkoolkat, and the SoundCloud hashtags for tracks on the album include labels like “Smanje-Manje rap”, “Primustof”, “vaporwave rap”, “New Age kwaito”, “township sounds” (this track is a soundscape of car spinning and skateboarding), and “digital scathamiya”. The tracks on the album all sound as varied and independent as their SoundCloud hashtags, with a tremendous amount of stylistic exploration from Okmalumkoolkat. <br/> <br/>
                    “Gqi!” is labeled as a “gqomwave” track, but what is gqomwave? At first, it seems that the Rudeboyz-produced beat that the track opens with would not be out of place next to Rudeboyz’s classic “Mercedes Song” or “Mitsubishi Song” from their “Rudeboyz” EP released on London-based label Goon Club Allstars in 2015. Punching kicks and noisy, growling vocal samples (often manipulated from kwaito samples) with sparse snare hits feels like the endless tension of classic gqom as Okmalumkoolkat sprinkles on adlibs and shout-outs. The departure from classic gqom comes at the drop of rapper duo Amadando’s heavy-hitting hook lines, with the simultaneous addition of the dark synth drone underneath. By accenting the static drone with catchy hook lines, the hook section creates a feeling of arrival, which is often foreign or completely non-existent in gqom tracks, but preserves the paranoid sense of instability and danceable broken beat. Okmalumkoolkat’s blended Zulu and English (with a dash of Xhosa and a line of Swahili) verses enter while all elements drop out except the backbeat vocal samples, and like flipping a magic switch, the gqom drone jumps up in pitch to create a trap horn section. Just by repurposing sounds that were already there, the songs pivots from gqom to something that would not be unusual on an American hip-hop party track. The trap aesthetic is further created by trading the punching gqom kicks for a tuned 808 bassline, adding melody to an otherwise static form. A clave line of sharp snares and melodic synths rise up along with Zwane’s raps, building and building, before everything drops out, pauses, and a riser slams the listener back into the gqom hook section. The titular word “gqi” repeated throughout the hook is onomatopoeia that means, “to appear”, and according to the Rap Genius translation, the hook roughly translates as “I do not know what happened, the beat just appeared and everyone started dancing,” which is exactly what happens. This cycle repeats for the rest of the track, alternating between gqom and its related trap hybrid. <br/> <br/>
                    At no point do any of the stylistic changes feel unpleasantly abrupt or forced. Both the trap elements and gqom elements feed on and support each other, while both supporting Okmalumkoolkat’s raps. Every element in the track is purposive, down to the tone of each performer’s raps, with Amadando’s hook stated as a drone, with minimal motion and each word drawn out, often on beat, while Okmalumkoolkat’s rhymes rise up in energy and dance around during the trap fusion sections. The two styles independently exist as fairly sparse, modular sets of elements. In the case of trap, heavy, offbeat 808 basslines, crisp snares and hats with plenty of triplets and pitched rolls, and contrastingly high synth lines can and have meshed with many other artists before, permeating everything from its origins in the Atlanta hip-hop scene through to the ever evolving pop of Taylor Swift. “Gqi!” takes these elements and fuses them perfectly with the droning synths and broken beats of gqom, creating a gqom track that has something very important to South African listeners: Western appeal. From the imagery and style of the video, it is clear that sonically meshing Durban sounds with American sounds is only half of the equation for popularity. <br/> <br/>
                    Rudeboyz kept their gqomwave coming in 2017 with their Goon Club Allstars EP “Gqomwave” released in November. The four tracks on the album each feel different and portray an interesting shift from their previous Goon Club Allstars release, the classic “Rudeboyz” EP, which contained tracks like “Mercedes Song” and “Mitsubishi Song” (both car brands are also popular brands of ecstasy). These tracks provide some of the prototypical sounds of gqom, and were some of the first gqom tracks to hit the international market. Each track on “Gqomwave” seems to fan out in a different direction, indicative of Rudeboyz’s development as artists and access to international resources, mentors, and industry. The opening track “Major Turn Up” fit right in on the “Rudeboyz” EP, with its slapping, sharp drums, repeating vocal chops, and dark strings making up tense, static chord hits. “Major Turn Up”, lacking a string or synth drone, has less pressure than other Rudeboyz tracks, and almost feels more upbeat. The third track, “No Mercy”, is a return to heavy, dark, paranoid form with its relentless kick and sub combo drilling the bass through you, and the rattling, broken samples and vocal barks and growls taking on a much more sinister character. “As’Jableni” has a four-on-the-floor kick in sghubu style, but this track is neither lighter nor more melodic. Despite its simple kick pattern, the other elements swirl around the booming kicks in polyrhythmic fashion, reminiscent of a dark, industrial European techno beat. </p>
                    <iframe scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/342201077&amp;color=%23ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;show_teaser=true&amp;visual=true"></iframe> 
                    <p>The most stunningly different track on the EP is “Bounce Back”, which maintains the dark aesthetics and sound selection of gqom, but morphs the beat into a headnodic, slow motion halftime groove, reminiscent of dubstep or dub. The alternating low/high pitched noise bursts on the halftime downbeats create the scaffold, as acoustic African drumming (a departure from the usual palette of synthesized sounds or mangled samples) fills the timeline atop pulsing sub bass patterns. More sonic discussion of Bounce Back.</p>


	

	                       
	                   </div>
                </section>

            </div>
        )
    }
}

export default Paper;
